from calculations.equations.HE_eq import *
from calculations.equations.MM_eq import *
from calculations.equations.PPM_eq import *
from calculations.equations.TC_eq import *
from calculations.equations.INH_eq import *
from calculations.equations.CI_eq import *
from calculations.equations.MA_eq import *
from calculations.equations.NCI_eq import *
from calculations.equations.MI_eq import *
from calculations.equations.SA_eq import *
from calculations.equations.SUA_eq import *
from calculations.equations.UCI_eq import *
