# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/ws/iceland/itc_software/qt_desing/main.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1114, 670)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.NewProButton = QtGui.QPushButton(self.centralwidget)
        self.NewProButton.setObjectName(_fromUtf8("NewProButton"))
        self.verticalLayout_3.addWidget(self.NewProButton)
        self.LoadButton = QtGui.QPushButton(self.centralwidget)
        self.LoadButton.setObjectName(_fromUtf8("LoadButton"))
        self.verticalLayout_3.addWidget(self.LoadButton)
        self.RewBut = QtGui.QPushButton(self.centralwidget)
        self.RewBut.setObjectName(_fromUtf8("RewBut"))
        self.verticalLayout_3.addWidget(self.RewBut)
        self.SolExpButton = QtGui.QPushButton(self.centralwidget)
        self.SolExpButton.setObjectName(_fromUtf8("SolExpButton"))
        self.verticalLayout_3.addWidget(self.SolExpButton)
        self.BatchButton = QtGui.QPushButton(self.centralwidget)
        self.BatchButton.setObjectName(_fromUtf8("BatchButton"))
        self.verticalLayout_3.addWidget(self.BatchButton)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.Extrap1 = QtGui.QSpinBox(self.centralwidget)
        self.Extrap1.setMaximum(100)
        self.Extrap1.setObjectName(_fromUtf8("Extrap1"))
        self.gridLayout.addWidget(self.Extrap1, 4, 1, 1, 1)
        self.Extrap2 = QtGui.QSpinBox(self.centralwidget)
        self.Extrap2.setMaximum(100)
        self.Extrap2.setObjectName(_fromUtf8("Extrap2"))
        self.gridLayout.addWidget(self.Extrap2, 4, 3, 1, 1)
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 4, 0, 1, 1)
        self.RepParab1 = QtGui.QCheckBox(self.centralwidget)
        self.RepParab1.setObjectName(_fromUtf8("RepParab1"))
        self.GraphBG1 = QtGui.QButtonGroup(MainWindow)
        self.GraphBG1.setObjectName(_fromUtf8("GraphBG1"))
        self.GraphBG1.setExclusive(False)
        self.GraphBG1.addButton(self.RepParab1)
        self.gridLayout.addWidget(self.RepParab1, 2, 1, 1, 1)
        self.GlobParab2 = QtGui.QCheckBox(self.centralwidget)
        self.GlobParab2.setObjectName(_fromUtf8("GlobParab2"))
        self.GraphBG2 = QtGui.QButtonGroup(MainWindow)
        self.GraphBG2.setObjectName(_fromUtf8("GraphBG2"))
        self.GraphBG2.setExclusive(False)
        self.GraphBG2.addButton(self.GlobParab2)
        self.gridLayout.addWidget(self.GlobParab2, 3, 3, 1, 1)
        self.Leg2Box = QtGui.QCheckBox(self.centralwidget)
        self.Leg2Box.setObjectName(_fromUtf8("Leg2Box"))
        self.gridLayout.addWidget(self.Leg2Box, 1, 2, 1, 1)
        self.RepLin2 = QtGui.QCheckBox(self.centralwidget)
        self.RepLin2.setObjectName(_fromUtf8("RepLin2"))
        self.GraphBG2.addButton(self.RepLin2)
        self.gridLayout.addWidget(self.RepLin2, 2, 2, 1, 1)
        self.Graph1Sel = QtGui.QComboBox(self.centralwidget)
        self.Graph1Sel.setObjectName(_fromUtf8("Graph1Sel"))
        self.Graph1Sel.addItem(_fromUtf8(""))
        self.Graph1Sel.addItem(_fromUtf8(""))
        self.Graph1Sel.addItem(_fromUtf8(""))
        self.Graph1Sel.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.Graph1Sel, 0, 0, 1, 1)
        self.Graph2Sel = QtGui.QComboBox(self.centralwidget)
        self.Graph2Sel.setObjectName(_fromUtf8("Graph2Sel"))
        self.Graph2Sel.addItem(_fromUtf8(""))
        self.Graph2Sel.addItem(_fromUtf8(""))
        self.Graph2Sel.addItem(_fromUtf8(""))
        self.Graph2Sel.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.Graph2Sel, 0, 2, 1, 1)
        self.RepParab2 = QtGui.QCheckBox(self.centralwidget)
        self.RepParab2.setObjectName(_fromUtf8("RepParab2"))
        self.GraphBG2.addButton(self.RepParab2)
        self.gridLayout.addWidget(self.RepParab2, 2, 3, 1, 1)
        self.GlobParab1 = QtGui.QCheckBox(self.centralwidget)
        self.GlobParab1.setObjectName(_fromUtf8("GlobParab1"))
        self.GraphBG1.addButton(self.GlobParab1)
        self.gridLayout.addWidget(self.GlobParab1, 3, 1, 1, 1)
        self.GlobLin2 = QtGui.QCheckBox(self.centralwidget)
        self.GlobLin2.setObjectName(_fromUtf8("GlobLin2"))
        self.GraphBG2.addButton(self.GlobLin2)
        self.gridLayout.addWidget(self.GlobLin2, 3, 2, 1, 1)
        self.GlobLin1 = QtGui.QCheckBox(self.centralwidget)
        self.GlobLin1.setObjectName(_fromUtf8("GlobLin1"))
        self.GraphBG1.addButton(self.GlobLin1)
        self.gridLayout.addWidget(self.GlobLin1, 3, 0, 1, 1)
        self.Leg1Box = QtGui.QCheckBox(self.centralwidget)
        self.Leg1Box.setObjectName(_fromUtf8("Leg1Box"))
        self.gridLayout.addWidget(self.Leg1Box, 1, 0, 1, 1)
        self.RepLin1 = QtGui.QCheckBox(self.centralwidget)
        self.RepLin1.setObjectName(_fromUtf8("RepLin1"))
        self.GraphBG1.addButton(self.RepLin1)
        self.gridLayout.addWidget(self.RepLin1, 2, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 4, 2, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.StatusLab = QtGui.QLabel(self.centralwidget)
        self.StatusLab.setObjectName(_fromUtf8("StatusLab"))
        self.verticalLayout_2.addWidget(self.StatusLab)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem1)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.horizontalLayout.addLayout(self.horizontalLayout_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1114, 26))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionSave_input_data = QtGui.QAction(MainWindow)
        self.actionSave_input_data.setObjectName(_fromUtf8("actionSave_input_data"))
        self.actionLoad_input_data = QtGui.QAction(MainWindow)
        self.actionLoad_input_data.setObjectName(_fromUtf8("actionLoad_input_data"))
        self.actionNew_project = QtGui.QAction(MainWindow)
        self.actionNew_project.setObjectName(_fromUtf8("actionNew_project"))
        self.actionExport_data_xls = QtGui.QAction(MainWindow)
        self.actionExport_data_xls.setObjectName(_fromUtf8("actionExport_data_xls"))
        self.actionImport_table = QtGui.QAction(MainWindow)
        self.actionImport_table.setObjectName(_fromUtf8("actionImport_table"))
        self.actionImport_table_Substrate_B = QtGui.QAction(MainWindow)
        self.actionImport_table_Substrate_B.setObjectName(_fromUtf8("actionImport_table_Substrate_B"))
        self.menuFile.addAction(self.actionNew_project)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave_input_data)
        self.menuFile.addAction(self.actionLoad_input_data)
        self.menuFile.addAction(self.actionExport_data_xls)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionImport_table)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "ReactionAnalyzer", None))
        self.NewProButton.setText(_translate("MainWindow", "Setup project", None))
        self.LoadButton.setText(_translate("MainWindow", "Load Data", None))
        self.RewBut.setText(_translate("MainWindow", "Review Data", None))
        self.SolExpButton.setText(_translate("MainWindow", "Fit to models", None))
        self.BatchButton.setText(_translate("MainWindow", "Batch run", None))
        self.label.setText(_translate("MainWindow", "Extrapolation %:", None))
        self.RepParab1.setText(_translate("MainWindow", "Parabola fit", None))
        self.GlobParab2.setText(_translate("MainWindow", "Global parabola", None))
        self.Leg2Box.setText(_translate("MainWindow", "Legend", None))
        self.RepLin2.setText(_translate("MainWindow", "Linear fit", None))
        self.Graph1Sel.setItemText(0, _translate("MainWindow", "Michaelis-Menten [V vs S]", None))
        self.Graph1Sel.setItemText(1, _translate("MainWindow", "Lineweaver-Buck [1/V vs 1/S]", None))
        self.Graph1Sel.setItemText(2, _translate("MainWindow", "Hans-Woolf [S/V vs S]", None))
        self.Graph1Sel.setItemText(3, _translate("MainWindow", "Eadue-Hofstee [V vs V/S]", None))
        self.Graph2Sel.setItemText(0, _translate("MainWindow", "Michaelis-Menten [V vs S]", None))
        self.Graph2Sel.setItemText(1, _translate("MainWindow", "Lineweaver-Buck [1/V vs 1/S]", None))
        self.Graph2Sel.setItemText(2, _translate("MainWindow", "Hans-Woolf [S/V vs S]", None))
        self.Graph2Sel.setItemText(3, _translate("MainWindow", "Eadue-Hofstee [V vs V/S]", None))
        self.RepParab2.setText(_translate("MainWindow", "Parabola fit", None))
        self.GlobParab1.setText(_translate("MainWindow", "Global parabola", None))
        self.GlobLin2.setText(_translate("MainWindow", "Global linear fit", None))
        self.GlobLin1.setText(_translate("MainWindow", "Global linear fit", None))
        self.Leg1Box.setText(_translate("MainWindow", "Legend", None))
        self.RepLin1.setText(_translate("MainWindow", "Linear fit", None))
        self.label_2.setText(_translate("MainWindow", "Extrapolation %:", None))
        self.StatusLab.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt; font-weight:600; color:#680000 ;\">FITTING DATA ...</span></p></body></html>", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.actionSave_input_data.setText(_translate("MainWindow", "Save data (*.pkl)", None))
        self.actionLoad_input_data.setText(_translate("MainWindow", "Import data (*.pkl)", None))
        self.actionNew_project.setText(_translate("MainWindow", "New project", None))
        self.actionExport_data_xls.setText(_translate("MainWindow", "Export data (*.xls)", None))
        self.actionImport_table.setText(_translate("MainWindow", "Import double substrate table", None))
        self.actionImport_table_Substrate_B.setText(_translate("MainWindow", "Import table (Substrate B)", None))


class MainWindow(QtGui.QMainWindow, Ui_MainWindow):
    def __init__(self, parent=None, f=QtCore.Qt.WindowFlags()):
        QtGui.QMainWindow.__init__(self, parent, f)

        self.setupUi(self)

