# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'solutionexplorer.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_SolutionExplorer(object):
    def setupUi(self, SolutionExplorer):
        SolutionExplorer.setObjectName(_fromUtf8("SolutionExplorer"))
        SolutionExplorer.resize(1152, 883)
        self.horizontalLayout = QtGui.QHBoxLayout(SolutionExplorer)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.Val6 = QtGui.QDoubleSpinBox(SolutionExplorer)
        self.Val6.setMaximum(99999999.0)
        self.Val6.setProperty("value", 1.0)
        self.Val6.setObjectName(_fromUtf8("Val6"))
        self.gridLayout.addWidget(self.Val6, 17, 1, 1, 1)
        self.Slider6 = QtGui.QSlider(SolutionExplorer)
        self.Slider6.setOrientation(QtCore.Qt.Horizontal)
        self.Slider6.setObjectName(_fromUtf8("Slider6"))
        self.gridLayout.addWidget(self.Slider6, 18, 1, 1, 1)
        self.line_6 = QtGui.QFrame(SolutionExplorer)
        self.line_6.setFrameShape(QtGui.QFrame.HLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.gridLayout.addWidget(self.line_6, 19, 1, 1, 1)
        self.Param6 = QtGui.QLabel(SolutionExplorer)
        self.Param6.setObjectName(_fromUtf8("Param6"))
        self.gridLayout.addWidget(self.Param6, 17, 0, 1, 1)
        self.line_5 = QtGui.QFrame(SolutionExplorer)
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.gridLayout.addWidget(self.line_5, 16, 1, 1, 1)
        self.Param1 = QtGui.QLabel(SolutionExplorer)
        self.Param1.setObjectName(_fromUtf8("Param1"))
        self.gridLayout.addWidget(self.Param1, 2, 0, 1, 1)
        self.label_2 = QtGui.QLabel(SolutionExplorer)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.Val1 = QtGui.QDoubleSpinBox(SolutionExplorer)
        self.Val1.setDecimals(5)
        self.Val1.setMinimum(0.0)
        self.Val1.setMaximum(99999999.0)
        self.Val1.setProperty("value", 1.0)
        self.Val1.setObjectName(_fromUtf8("Val1"))
        self.gridLayout.addWidget(self.Val1, 2, 1, 1, 1)
        self.Slider1 = QtGui.QSlider(SolutionExplorer)
        self.Slider1.setOrientation(QtCore.Qt.Horizontal)
        self.Slider1.setObjectName(_fromUtf8("Slider1"))
        self.gridLayout.addWidget(self.Slider1, 3, 1, 1, 1)
        self.line_1 = QtGui.QFrame(SolutionExplorer)
        self.line_1.setFrameShape(QtGui.QFrame.HLine)
        self.line_1.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_1.setObjectName(_fromUtf8("line_1"))
        self.gridLayout.addWidget(self.line_1, 4, 1, 1, 1)
        self.Param2 = QtGui.QLabel(SolutionExplorer)
        self.Param2.setObjectName(_fromUtf8("Param2"))
        self.gridLayout.addWidget(self.Param2, 5, 0, 1, 1)
        self.Val2 = QtGui.QDoubleSpinBox(SolutionExplorer)
        self.Val2.setDecimals(5)
        self.Val2.setMaximum(99999999.0)
        self.Val2.setProperty("value", 1.0)
        self.Val2.setObjectName(_fromUtf8("Val2"))
        self.gridLayout.addWidget(self.Val2, 5, 1, 1, 1)
        self.line = QtGui.QFrame(SolutionExplorer)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout.addWidget(self.line, 1, 1, 1, 1)
        self.EqSel = QtGui.QComboBox(SolutionExplorer)
        self.EqSel.setObjectName(_fromUtf8("EqSel"))
        self.gridLayout.addWidget(self.EqSel, 0, 1, 1, 1)
        self.Param3 = QtGui.QLabel(SolutionExplorer)
        self.Param3.setObjectName(_fromUtf8("Param3"))
        self.gridLayout.addWidget(self.Param3, 8, 0, 1, 1)
        self.Slider2 = QtGui.QSlider(SolutionExplorer)
        self.Slider2.setOrientation(QtCore.Qt.Horizontal)
        self.Slider2.setObjectName(_fromUtf8("Slider2"))
        self.gridLayout.addWidget(self.Slider2, 6, 1, 1, 1)
        self.Val3 = QtGui.QDoubleSpinBox(SolutionExplorer)
        self.Val3.setDecimals(5)
        self.Val3.setMaximum(99999999.0)
        self.Val3.setProperty("value", 1.0)
        self.Val3.setObjectName(_fromUtf8("Val3"))
        self.gridLayout.addWidget(self.Val3, 8, 1, 1, 1)
        self.Slider3 = QtGui.QSlider(SolutionExplorer)
        self.Slider3.setOrientation(QtCore.Qt.Horizontal)
        self.Slider3.setObjectName(_fromUtf8("Slider3"))
        self.gridLayout.addWidget(self.Slider3, 9, 1, 1, 1)
        self.line_3 = QtGui.QFrame(SolutionExplorer)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.gridLayout.addWidget(self.line_3, 10, 1, 1, 1)
        self.line_2 = QtGui.QFrame(SolutionExplorer)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.gridLayout.addWidget(self.line_2, 7, 1, 1, 1)
        self.Param4 = QtGui.QLabel(SolutionExplorer)
        self.Param4.setObjectName(_fromUtf8("Param4"))
        self.gridLayout.addWidget(self.Param4, 11, 0, 1, 1)
        self.Slider4 = QtGui.QSlider(SolutionExplorer)
        self.Slider4.setOrientation(QtCore.Qt.Horizontal)
        self.Slider4.setObjectName(_fromUtf8("Slider4"))
        self.gridLayout.addWidget(self.Slider4, 12, 1, 1, 1)
        self.line_4 = QtGui.QFrame(SolutionExplorer)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.gridLayout.addWidget(self.line_4, 13, 1, 1, 1)
        self.Val4 = QtGui.QDoubleSpinBox(SolutionExplorer)
        self.Val4.setDecimals(5)
        self.Val4.setMaximum(99999999.0)
        self.Val4.setProperty("value", 1.0)
        self.Val4.setObjectName(_fromUtf8("Val4"))
        self.gridLayout.addWidget(self.Val4, 11, 1, 1, 1)
        self.Param5 = QtGui.QLabel(SolutionExplorer)
        self.Param5.setObjectName(_fromUtf8("Param5"))
        self.gridLayout.addWidget(self.Param5, 14, 0, 1, 1)
        self.Slider5 = QtGui.QSlider(SolutionExplorer)
        self.Slider5.setOrientation(QtCore.Qt.Horizontal)
        self.Slider5.setObjectName(_fromUtf8("Slider5"))
        self.gridLayout.addWidget(self.Slider5, 15, 1, 1, 1)
        self.Val5 = QtGui.QDoubleSpinBox(SolutionExplorer)
        self.Val5.setDecimals(5)
        self.Val5.setMaximum(99999999.0)
        self.Val5.setProperty("value", 1.0)
        self.Val5.setObjectName(_fromUtf8("Val5"))
        self.gridLayout.addWidget(self.Val5, 14, 1, 1, 1)
        self.ulab1 = QtGui.QLabel(SolutionExplorer)
        self.ulab1.setText(_fromUtf8(""))
        self.ulab1.setObjectName(_fromUtf8("ulab1"))
        self.gridLayout.addWidget(self.ulab1, 2, 2, 1, 1)
        self.ulab2 = QtGui.QLabel(SolutionExplorer)
        self.ulab2.setText(_fromUtf8(""))
        self.ulab2.setObjectName(_fromUtf8("ulab2"))
        self.gridLayout.addWidget(self.ulab2, 5, 2, 1, 1)
        self.ulab3 = QtGui.QLabel(SolutionExplorer)
        self.ulab3.setText(_fromUtf8(""))
        self.ulab3.setObjectName(_fromUtf8("ulab3"))
        self.gridLayout.addWidget(self.ulab3, 8, 2, 1, 1)
        self.ulab4 = QtGui.QLabel(SolutionExplorer)
        self.ulab4.setText(_fromUtf8(""))
        self.ulab4.setObjectName(_fromUtf8("ulab4"))
        self.gridLayout.addWidget(self.ulab4, 11, 2, 1, 1)
        self.ulab5 = QtGui.QLabel(SolutionExplorer)
        self.ulab5.setText(_fromUtf8(""))
        self.ulab5.setObjectName(_fromUtf8("ulab5"))
        self.gridLayout.addWidget(self.ulab5, 14, 2, 1, 1)
        self.ulab6 = QtGui.QLabel(SolutionExplorer)
        self.ulab6.setText(_fromUtf8(""))
        self.ulab6.setObjectName(_fromUtf8("ulab6"))
        self.gridLayout.addWidget(self.ulab6, 17, 2, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.set_fit_widget = QtGui.QWidget(SolutionExplorer)
        self.set_fit_widget.setObjectName(_fromUtf8("set_fit_widget"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.set_fit_widget)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.set_fit_widget_2 = QtGui.QWidget(self.set_fit_widget)
        self.set_fit_widget_2.setObjectName(_fromUtf8("set_fit_widget_2"))
        self.formLayout = QtGui.QFormLayout(self.set_fit_widget_2)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_15 = QtGui.QLabel(self.set_fit_widget_2)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_15)
        self.setsel = QtGui.QComboBox(self.set_fit_widget_2)
        self.setsel.setObjectName(_fromUtf8("setsel"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.setsel)
        self.fitlab1 = QtGui.QLabel(self.set_fit_widget_2)
        self.fitlab1.setObjectName(_fromUtf8("fitlab1"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.fitlab1)
        self.vallab1 = QtGui.QLabel(self.set_fit_widget_2)
        self.vallab1.setObjectName(_fromUtf8("vallab1"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.vallab1)
        self.fitlab2 = QtGui.QLabel(self.set_fit_widget_2)
        self.fitlab2.setObjectName(_fromUtf8("fitlab2"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.fitlab2)
        self.vallab2 = QtGui.QLabel(self.set_fit_widget_2)
        self.vallab2.setObjectName(_fromUtf8("vallab2"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.vallab2)
        self.fitlab3 = QtGui.QLabel(self.set_fit_widget_2)
        self.fitlab3.setObjectName(_fromUtf8("fitlab3"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.fitlab3)
        self.vallab3 = QtGui.QLabel(self.set_fit_widget_2)
        self.vallab3.setObjectName(_fromUtf8("vallab3"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.vallab3)
        self.fitlab4 = QtGui.QLabel(self.set_fit_widget_2)
        self.fitlab4.setObjectName(_fromUtf8("fitlab4"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.fitlab4)
        self.vallab4 = QtGui.QLabel(self.set_fit_widget_2)
        self.vallab4.setObjectName(_fromUtf8("vallab4"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.vallab4)
        self.fitlab5 = QtGui.QLabel(self.set_fit_widget_2)
        self.fitlab5.setObjectName(_fromUtf8("fitlab5"))
        self.formLayout.setWidget(7, QtGui.QFormLayout.LabelRole, self.fitlab5)
        self.vallab5 = QtGui.QLabel(self.set_fit_widget_2)
        self.vallab5.setObjectName(_fromUtf8("vallab5"))
        self.formLayout.setWidget(7, QtGui.QFormLayout.FieldRole, self.vallab5)
        self.fitlab6 = QtGui.QLabel(self.set_fit_widget_2)
        self.fitlab6.setObjectName(_fromUtf8("fitlab6"))
        self.formLayout.setWidget(8, QtGui.QFormLayout.LabelRole, self.fitlab6)
        self.vallab6 = QtGui.QLabel(self.set_fit_widget_2)
        self.vallab6.setObjectName(_fromUtf8("vallab6"))
        self.formLayout.setWidget(8, QtGui.QFormLayout.FieldRole, self.vallab6)
        self.verticalLayout_4.addWidget(self.set_fit_widget_2)
        self.ReFitSet = QtGui.QPushButton(self.set_fit_widget)
        self.ReFitSet.setObjectName(_fromUtf8("ReFitSet"))
        self.verticalLayout_4.addWidget(self.ReFitSet)
        self.SetParams = QtGui.QPushButton(self.set_fit_widget)
        self.SetParams.setObjectName(_fromUtf8("SetParams"))
        self.verticalLayout_4.addWidget(self.SetParams)
        self.verticalLayout_3.addWidget(self.set_fit_widget)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.line_7 = QtGui.QFrame(SolutionExplorer)
        self.line_7.setFrameShape(QtGui.QFrame.HLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName(_fromUtf8("line_7"))
        self.verticalLayout_3.addWidget(self.line_7)
        self.formLayout_5 = QtGui.QFormLayout()
        self.formLayout_5.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_5.setObjectName(_fromUtf8("formLayout_5"))
        self.AjdButVal = QtGui.QPushButton(SolutionExplorer)
        self.AjdButVal.setObjectName(_fromUtf8("AjdButVal"))
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.LabelRole, self.AjdButVal)
        self.AutoFitBut = QtGui.QPushButton(SolutionExplorer)
        self.AutoFitBut.setObjectName(_fromUtf8("AutoFitBut"))
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.FieldRole, self.AutoFitBut)
        self.verticalLayout_3.addLayout(self.formLayout_5)
        self.formLayout_3 = QtGui.QFormLayout()
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.label_3 = QtGui.QLabel(SolutionExplorer)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_3)
        self.ResLab = QtGui.QLabel(SolutionExplorer)
        self.ResLab.setObjectName(_fromUtf8("ResLab"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.ResLab)
        self.verticalLayout_3.addLayout(self.formLayout_3)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.line_9 = QtGui.QFrame(SolutionExplorer)
        self.line_9.setFrameShape(QtGui.QFrame.VLine)
        self.line_9.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_9.setObjectName(_fromUtf8("line_9"))
        self.horizontalLayout.addWidget(self.line_9)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.formLayout_4 = QtGui.QFormLayout()
        self.formLayout_4.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_4.setObjectName(_fromUtf8("formLayout_4"))
        self.PlotLab = QtGui.QLabel(SolutionExplorer)
        self.PlotLab.setObjectName(_fromUtf8("PlotLab"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.LabelRole, self.PlotLab)
        self.PlotCB = QtGui.QComboBox(SolutionExplorer)
        self.PlotCB.setObjectName(_fromUtf8("PlotCB"))
        self.PlotCB.addItem(_fromUtf8(""))
        self.PlotCB.addItem(_fromUtf8(""))
        self.PlotCB.addItem(_fromUtf8(""))
        self.PlotCB.addItem(_fromUtf8(""))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.FieldRole, self.PlotCB)
        self.SubLab = QtGui.QLabel(SolutionExplorer)
        self.SubLab.setObjectName(_fromUtf8("SubLab"))
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.LabelRole, self.SubLab)
        self.SetCB = QtGui.QComboBox(SolutionExplorer)
        self.SetCB.setObjectName(_fromUtf8("SetCB"))
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.FieldRole, self.SetCB)
        self.ErrCB = QtGui.QComboBox(SolutionExplorer)
        self.ErrCB.setObjectName(_fromUtf8("ErrCB"))
        self.ErrCB.addItem(_fromUtf8(""))
        self.ErrCB.addItem(_fromUtf8(""))
        self.formLayout_4.setWidget(3, QtGui.QFormLayout.FieldRole, self.ErrCB)
        self.ErrLAb = QtGui.QLabel(SolutionExplorer)
        self.ErrLAb.setObjectName(_fromUtf8("ErrLAb"))
        self.formLayout_4.setWidget(3, QtGui.QFormLayout.LabelRole, self.ErrLAb)
        self.EncLab = QtGui.QLabel(SolutionExplorer)
        self.EncLab.setObjectName(_fromUtf8("EncLab"))
        self.formLayout_4.setWidget(4, QtGui.QFormLayout.LabelRole, self.EncLab)
        self.LegendCB = QtGui.QCheckBox(SolutionExplorer)
        self.LegendCB.setObjectName(_fromUtf8("LegendCB"))
        self.formLayout_4.setWidget(5, QtGui.QFormLayout.LabelRole, self.LegendCB)
        self.EncCB = QtGui.QComboBox(SolutionExplorer)
        self.EncCB.setObjectName(_fromUtf8("EncCB"))
        self.EncCB.addItem(_fromUtf8(""))
        self.formLayout_4.setWidget(4, QtGui.QFormLayout.FieldRole, self.EncCB)
        self.verticalLayout.addLayout(self.formLayout_4)
        self.line_8 = QtGui.QFrame(SolutionExplorer)
        self.line_8.setFrameShape(QtGui.QFrame.HLine)
        self.line_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_8.setObjectName(_fromUtf8("line_8"))
        self.verticalLayout.addWidget(self.line_8)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.equation = QtGui.QLabel(SolutionExplorer)
        self.equation.setObjectName(_fromUtf8("equation"))
        self.horizontalLayout_2.addWidget(self.equation)
        self.EqPic = QtGui.QLabel(SolutionExplorer)
        self.EqPic.setObjectName(_fromUtf8("EqPic"))
        self.horizontalLayout_2.addWidget(self.EqPic)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem3 = QtGui.QSpacerItem(1300, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem3)
        self.horizontalLayout.addLayout(self.verticalLayout)

        self.retranslateUi(SolutionExplorer)
        QtCore.QMetaObject.connectSlotsByName(SolutionExplorer)

    def retranslateUi(self, SolutionExplorer):
        SolutionExplorer.setWindowTitle(_translate("SolutionExplorer", "Form", None))
        self.Param6.setText(_translate("SolutionExplorer", "TextLabel", None))
        self.Param1.setText(_translate("SolutionExplorer", "TextLabel", None))
        self.label_2.setText(_translate("SolutionExplorer", "Kinetics:", None))
        self.Param2.setText(_translate("SolutionExplorer", "TextLabel", None))
        self.Param3.setText(_translate("SolutionExplorer", "TextLabel", None))
        self.Param4.setText(_translate("SolutionExplorer", "TextLabel", None))
        self.Param5.setText(_translate("SolutionExplorer", "TextLabel", None))
        self.label_15.setText(_translate("SolutionExplorer", "Set number", None))
        self.fitlab1.setText(_translate("SolutionExplorer", "TextLabel", None))
        self.vallab1.setText(_translate("SolutionExplorer", "TextLabel", None))
        self.fitlab2.setText(_translate("SolutionExplorer", "TextLabel", None))
        self.vallab2.setText(_translate("SolutionExplorer", "TextLabel", None))
        self.fitlab3.setText(_translate("SolutionExplorer", "TextLabel", None))
        self.vallab3.setText(_translate("SolutionExplorer", "TextLabel", None))
        self.fitlab4.setText(_translate("SolutionExplorer", "TextLabel", None))
        self.vallab4.setText(_translate("SolutionExplorer", "TextLabel", None))
        self.fitlab5.setText(_translate("SolutionExplorer", "TextLabel", None))
        self.vallab5.setText(_translate("SolutionExplorer", "TextLabel", None))
        self.fitlab6.setText(_translate("SolutionExplorer", "TextLabel", None))
        self.vallab6.setText(_translate("SolutionExplorer", "TextLabel", None))
        self.ReFitSet.setText(_translate("SolutionExplorer", "Re-Fit set", None))
        self.SetParams.setText(_translate("SolutionExplorer", "Aplly to all", None))
        self.AjdButVal.setText(_translate("SolutionExplorer", "Adjust fit values", None))
        self.AutoFitBut.setText(_translate("SolutionExplorer", "Find fit - All", None))
        self.label_3.setText(_translate("SolutionExplorer", "Sum of residuals:", None))
        self.ResLab.setText(_translate("SolutionExplorer", "NA", None))
        self.PlotLab.setText(_translate("SolutionExplorer", "Plot View:", None))
        self.PlotCB.setItemText(0, _translate("SolutionExplorer", "Michaelis-Menten [V vs S]", None))
        self.PlotCB.setItemText(1, _translate("SolutionExplorer", "Lineweaver-Buck [1/V vs 1/S]", None))
        self.PlotCB.setItemText(2, _translate("SolutionExplorer", "Hans-Woolf [S/V vs S]", None))
        self.PlotCB.setItemText(3, _translate("SolutionExplorer", "Eadue-Hofstee [V vs V/S]", None))
        self.SubLab.setText(_translate("SolutionExplorer", "Variable substrate:", None))
        self.ErrCB.setItemText(0, _translate("SolutionExplorer", "Points", None))
        self.ErrCB.setItemText(1, _translate("SolutionExplorer", "Errors (min - max)", None))
        self.ErrLAb.setText(_translate("SolutionExplorer", "View:", None))
        self.EncLab.setText(_translate("SolutionExplorer", "Select set:", None))
        self.LegendCB.setText(_translate("SolutionExplorer", "Legend", None))
        self.EncCB.setItemText(0, _translate("SolutionExplorer", "All", None))
        self.equation.setText(_translate("SolutionExplorer", "Equation:", None))
        self.EqPic.setText(_translate("SolutionExplorer", "TextLabel", None))

