# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/ws/iceland/itc_software/qt_desing/twosubstr/load_data_ds.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_LoadDataDs(object):
    def setupUi(self, LoadDataDs):
        LoadDataDs.setObjectName(_fromUtf8("LoadDataDs"))
        LoadDataDs.resize(1076, 520)
        self.horizontalLayout = QtGui.QHBoxLayout(LoadDataDs)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.SubAName = QtGui.QLabel(LoadDataDs)
        self.SubAName.setObjectName(_fromUtf8("SubAName"))
        self.verticalLayout.addWidget(self.SubAName)
        self.SubAText = QtGui.QPlainTextEdit(LoadDataDs)
        self.SubAText.setObjectName(_fromUtf8("SubAText"))
        self.verticalLayout.addWidget(self.SubAText)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.SubBName = QtGui.QLabel(LoadDataDs)
        self.SubBName.setObjectName(_fromUtf8("SubBName"))
        self.verticalLayout_2.addWidget(self.SubBName)
        self.verticalWidget_2 = QtGui.QWidget(LoadDataDs)
        self.verticalWidget_2.setObjectName(_fromUtf8("verticalWidget_2"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.verticalWidget_2)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.SubBText = QtGui.QDoubleSpinBox(self.verticalWidget_2)
        self.SubBText.setDecimals(5)
        self.SubBText.setMaximum(100000.0)
        self.SubBText.setProperty("value", 1.0)
        self.SubBText.setObjectName(_fromUtf8("SubBText"))
        self.verticalLayout_6.addWidget(self.SubBText)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem)
        self.verticalLayout_2.addWidget(self.verticalWidget_2)
        self.line_2 = QtGui.QFrame(LoadDataDs)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.verticalLayout_2.addWidget(self.line_2)
        self.verticalWidget = QtGui.QWidget(LoadDataDs)
        self.verticalWidget.setObjectName(_fromUtf8("verticalWidget"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.verticalWidget)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.label = QtGui.QLabel(self.verticalWidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_5.addWidget(self.label)
        self.InitConc = QtGui.QDoubleSpinBox(self.verticalWidget)
        self.InitConc.setDecimals(5)
        self.InitConc.setMaximum(999999.0)
        self.InitConc.setProperty("value", 1.0)
        self.InitConc.setObjectName(_fromUtf8("InitConc"))
        self.verticalLayout_5.addWidget(self.InitConc)
        self.label_2 = QtGui.QLabel(self.verticalWidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_5.addWidget(self.label_2)
        self.TimeStep = QtGui.QDoubleSpinBox(self.verticalWidget)
        self.TimeStep.setDecimals(5)
        self.TimeStep.setMaximum(999999.0)
        self.TimeStep.setProperty("value", 1.0)
        self.TimeStep.setObjectName(_fromUtf8("TimeStep"))
        self.verticalLayout_5.addWidget(self.TimeStep)
        self.label_6 = QtGui.QLabel(self.verticalWidget)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout_5.addWidget(self.label_6)
        self.InitVol = QtGui.QDoubleSpinBox(self.verticalWidget)
        self.InitVol.setDecimals(4)
        self.InitVol.setMaximum(999.99)
        self.InitVol.setProperty("value", 1.0)
        self.InitVol.setObjectName(_fromUtf8("InitVol"))
        self.verticalLayout_5.addWidget(self.InitVol)
        self.label_8 = QtGui.QLabel(self.verticalWidget)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.verticalLayout_5.addWidget(self.label_8)
        self.AddVol = QtGui.QDoubleSpinBox(self.verticalWidget)
        self.AddVol.setDecimals(5)
        self.AddVol.setMaximum(999.99)
        self.AddVol.setProperty("value", 0.1)
        self.AddVol.setObjectName(_fromUtf8("AddVol"))
        self.verticalLayout_5.addWidget(self.AddVol)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem1)
        self.verticalLayout_2.addWidget(self.verticalWidget)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_3 = QtGui.QLabel(LoadDataDs)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_3.addWidget(self.label_3)
        self.RateText = QtGui.QPlainTextEdit(LoadDataDs)
        self.RateText.setObjectName(_fromUtf8("RateText"))
        self.verticalLayout_3.addWidget(self.RateText)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.AddRep = QtGui.QPushButton(LoadDataDs)
        self.AddRep.setObjectName(_fromUtf8("AddRep"))
        self.verticalLayout_4.addWidget(self.AddRep)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.verticalLayout_4.addItem(spacerItem2)
        self.SwitchSet = QtGui.QPushButton(LoadDataDs)
        self.SwitchSet.setObjectName(_fromUtf8("SwitchSet"))
        self.verticalLayout_4.addWidget(self.SwitchSet)
        self.SwitchRoles = QtGui.QPushButton(LoadDataDs)
        self.SwitchRoles.setObjectName(_fromUtf8("SwitchRoles"))
        self.verticalLayout_4.addWidget(self.SwitchRoles)
        self.line = QtGui.QFrame(LoadDataDs)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout_4.addWidget(self.line)
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_7 = QtGui.QLabel(LoadDataDs)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_7)
        self.label_5 = QtGui.QLabel(LoadDataDs)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_5)
        self.RepNu = QtGui.QLabel(LoadDataDs)
        self.RepNu.setObjectName(_fromUtf8("RepNu"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.RepNu)
        self.SetNu = QtGui.QLineEdit(LoadDataDs)
        self.SetNu.setObjectName(_fromUtf8("SetNu"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.SetNu)
        self.verticalLayout_4.addLayout(self.formLayout)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Ignored)
        self.verticalLayout_4.addItem(spacerItem3)
        self.OKButton = QtGui.QPushButton(LoadDataDs)
        self.OKButton.setObjectName(_fromUtf8("OKButton"))
        self.verticalLayout_4.addWidget(self.OKButton)
        self.CancelButton = QtGui.QPushButton(LoadDataDs)
        self.CancelButton.setObjectName(_fromUtf8("CancelButton"))
        self.verticalLayout_4.addWidget(self.CancelButton)
        self.horizontalLayout.addLayout(self.verticalLayout_4)

        self.retranslateUi(LoadDataDs)
        QtCore.QMetaObject.connectSlotsByName(LoadDataDs)

    def retranslateUi(self, LoadDataDs):
        LoadDataDs.setWindowTitle(_translate("LoadDataDs", "Dialog", None))
        self.SubAName.setText(_translate("LoadDataDs", "SubsA", None))
        self.SubBName.setText(_translate("LoadDataDs", "SubsB", None))
        self.label.setText(_translate("LoadDataDs", "Concentration", None))
        self.label_2.setText(_translate("LoadDataDs", "Injection spacing (time)", None))
        self.label_6.setText(_translate("LoadDataDs", "Initial Volume", None))
        self.label_8.setText(_translate("LoadDataDs", "Added Volume per injection ", None))
        self.label_3.setText(_translate("LoadDataDs", "Reaction rate", None))
        self.AddRep.setText(_translate("LoadDataDs", "Append replicate to set", None))
        self.SwitchSet.setText(_translate("LoadDataDs", "Next set", None))
        self.SwitchRoles.setText(_translate("LoadDataDs", "Switch substrate roles", None))
        self.label_7.setText(_translate("LoadDataDs", "Adding to set:", None))
        self.label_5.setText(_translate("LoadDataDs", "Replicates present:", None))
        self.RepNu.setText(_translate("LoadDataDs", "0", None))
        self.SetNu.setText(_translate("LoadDataDs", "Set 1", None))
        self.OKButton.setText(_translate("LoadDataDs", "Import", None))
        self.CancelButton.setText(_translate("LoadDataDs", "Cancel", None))


class LoadDataDs(QtGui.QDialog, Ui_LoadDataDs):
    def __init__(self, parent=None, f=QtCore.Qt.WindowFlags()):
        QtGui.QDialog.__init__(self, parent, f)

        self.setupUi(self)

